name: Build-test-deployAWSLambda
on: push

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      # Run testing on the code
      - name: Test
        run: go test ./... -v
  deploy-lambda:
    name: deploy
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
       # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
       # Run build
      - name: Build
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bootstrap main.go
          zip wishy.zip bootstrap
      - name: Install Serverless Framework
        run: npm install -g serverless
      # Zip build for lambda push
      - name: Deploy to AWS Lambda
        run: serverless deploy
        env:
          STAGE: prod
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
